### ISSUE TITLE
[FEAT] - Swagger Docs

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot-Project/api#9]

**Comment by Vyvy-vi** [comment]
I'd like to look into setting this up :D

**Comment by j-dogcoder** [comment]
That would be awsome @Vyvy-vi!

**Comment by nhcarrigan** [comment]
Hello!

Popping by to say that now that this API has been integrated in [Becca Lyria](https://github.com/beccalyria/discord-bot), we would greatly appreciate having some sort of documentation (even in a readme) for how to obtain an API token. We need somewhere to point contributors to when they're working on our features. 😁

**Comment by j-dogcoder** [comment]
Hey @nhcarrigan! I agree that it will be good to get some proper docs. I will follow up with @Vyvy-vi about this.

**Comment by j-dogcoder** [comment]
@Vyvy-vi Let me know if you need me to take this. 😄

**Comment by j-dogcoder** [comment]
Hey @nhcarrigan, The API now has docs! You can check them out at https://api.heptagrambotproject.com/api/docs.
